<?php

namespace AnnuaireBundle\Repository;

/**
 * AnnuaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnuaireRepository extends \Doctrine\ORM\EntityRepository
{
	public function recuperer_liste(){
		return $this
			->createQueryBuilder('a')
			->getQuery()
			->getArrayResult();
	}
}
